trigger:
- none

pool:
  name: Multi_Tier
  demands:
    - agent.name -equals Agent-1

stages:
  - stage: compile
    displayName: 'Maven Compile'
    jobs:
      - job: maven_compile
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'compile'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          
  - stage: test
    displayName: 'Maven test'
    jobs:
      - job: unit_test
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'test'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          
  - stage: trivy_fs_scan
    displayName: 'Trivy FS Scan'
    jobs:
      - job: trivy_fs_scan
        displayName: 'Trivy FS Scan'
        steps:
          - task: CmdLine@2
            inputs:
              script: 'trivy fs --format table -o fs.html .'
            
  - stage: sonarqube
    displayName: 'SonarAnalysis'
    jobs:
      - job: sonarqube_analysis
        displayName: 'SonarAnalysis'
        steps:
        - task: SonarQubePrepare@7
          inputs:
            SonarQube: 'sonar-svc'
            scannerMode: 'cli'
            configMode: 'manual'
            cliProjectKey: 'bankapp'
            cliProjectName: 'bankapp'
            cliSources: '.'
            extraProperties: 'sonar.java.binaries=.'
            
        - task: SonarQubeAnalyze@7
          inputs:
            jdkversion: 'JAVA_HOME_17_X64'

  - stage: publish_artifacts
    displayName: 'Publish_Build_Artifacts'
    jobs:
      - job: publish_artifacts
        displayName: 'Publish_Build_Artifacts'
        steps:
              
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean deploy'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          
          - task: MavenAuthenticate@0
            inputs:
              artifactsFeeds: 'bankapp-maven'

  - stage: docker_build
    displayName: 'Docker_Build'
    jobs:
      - job: docker_build
        displayName: 'Docker_Build'
        steps: 
        
          - task: CmdLine@2
            inputs:
              script: 'mvn package'
          - task: Docker@2
            inputs:
              containerRegistry: 'docker-svc'
              repository: 'dev'
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: 'latest'

  - stage: trivy_images_scan
    displayName: 'Trivy Images Scan'
    jobs:
      - job: trivy_images_scan
        displayName: 'Trivy Images Scan'
        steps:
          - task: CmdLine@2
            inputs:
              script: 'trivy image --format table -o image.html public.ecr.aws/dev:latest'

  - stage: docker_publish
    displayName: 'Docker_Publish'
    jobs:
      - job: docker_publish
        displayName: 'Docker_Publish'
        steps:

        - script: |
            aws ecr get-login-password --region $(AWS_REGION) | docker login --username AWS --password-stdin $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com
          displayName: 'Login to AWS'
          env:
            AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
            AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

        - task: Docker@2
          inputs:
            containerRegistry: 'docker-svc'
            repository: 'dev'
            command: 'push'
            tags: 'latest'
